### ISSUE TITLE
PG::TRSerializationFailure - canceling statement due to conflict with recovery

### ISSUE THREAD

**Issue by jimishjoban** [instacart/makara#106]
Hey guys,

Its a great Gem. Many thanks! We have used it to do setup Master Slave replication and we are now redirecting all our reads to Slave using this gem.

We faced into this issue recently:

ActiveRecord::StatementInvalid: PG::TRSerializationFailure: ERROR: canceling statement due to conflict with recovery DETAIL: User query might have needed to see row versions that must be removed

This error comes when the application server tries to read from Slave and it happens in very high load environment... 

Any suggestions/tips to overcome the error?

Thanks!

**Comment by bleonard** [comment]
I don't have much experience with PG or get many useful results from googling. @sax seen this one?

**Comment by Mothirajha** [comment]
@bleonard @sax   To solve ActiveRecord::StatementInvalid: PG::TRSerializationFailure: ERROR: canceling statement due to conflict, error we just increased our vacuum_defer_cleanup_age on Postgresql configuration. It helped us to fix the issue.

**Comment by beneggett** [comment]
@Mothirajha: Out of curiosity, what value did you change the `vacuum_defer_cleanup_age` to? My understanding is its a txn amount, not a time amount, but I'm not sure where to begin as a good starting value

**Comment by glaksmono** [comment]
@Mothirajha thoughts about @beneggett's question? I'm wondering the same thing CC @bleonard @sax

**Comment by Mothirajha** [comment]
@beneggett  sorry for the very late reply, vaccum_defer_cleanup_age value depends on the number of time write happens on your hot_standby_server (master).  We have updated the value from 0 to 200, which kind of sorted the issue.
**Reference**: https://www.postgresql.org/docs/9.4/static/runtime-config-replication.html

**Comment by beneggett** [comment]
No worries! After doing some research, what we actually ended up doing was setting `hot_standby_feedback` to  `1` (on) in lieu of messing with `vacuum_defer_cleanup_age`. The bottom comment in the link you just posted above sent got us there. Problems went away afterwards

**Comment by Mothirajha** [comment]
after changing the value of hot_standby_feedback did you face any lag in data replication or bloat on primary server?

**Comment by beneggett** [comment]
No, we did not. That actually cleaned up some of our replication lag issues

**Comment by Mothirajha** [comment]
Thanks @beneggett  will try hot_standby_feedback changes.
