### ISSUE TITLE
rubygems package

### ISSUE THREAD

**Issue by dreyks** [instacart/makara#107]
Will the gem be pushed to rubygems? right now there's a 2 year old version there, and github Gemfile option may not always be desireable

**Comment by bleonard** [comment]
through an unfortunate series of events, i do not have the rights there. anyone know someone at block.io
https://rubygems.org/gems/makara

Maybe @patricklodder based on https://github.com/blockio

@patricklodder if you have access there, can you please transfer to it us?

**Comment by bleonard** [comment]
Actually, maybe it is @doersf

Atif, can you give us access?

**Comment by bf4** [comment]
ref: https://github.com/rubygems/rubygems.org/issues/725

**Comment by bf4** [comment]
In the meantime you could release it as `taskrabbit-makara` like in the old github day s:)

**Comment by bleonard** [comment]
ok, master is an RC right now that we have to test out. when that's passed, i'll make up a new name.

unless there is an chance @doersf could run this on his command line?
`gem owner makara -a brian@bleonard.com`

**Comment by patricklodder** [comment]
I've pinged Atif through other channels for you :)

**Comment by doersf** [comment]
gem yanked, goodluck!

**Comment by bleonard** [comment]
Thanks @doersf 

update here. https://rubygems.org/gems/makara
