### ISSUE TITLE
Uneven load on slaves

### ISSUE THREAD

**Issue by pauldowman** [instacart/makara#110]
Hi, thanks for this awesome gem. We're just getting started with it and it looks amazing, very thorough! :smile:  

But the load seems to be very unbalanced and I think I don't understand the options correctly. If I want even load among the read-only followers what settings should I use?

We're using:

```
  blacklist_duration: 300
  master_ttl: 70
  master_strategy: round_robin
  sticky: false
```

I would have thought that `round_robin` would do it. And I'm confused about what `sticky` does. When I had `sticky: true` then all traffic went to master (for much longer than `master_ttl`).

Also, I submitted PR #109 to fix a couple of issues in the README.

**Comment by pauldowman** [comment]
Here's more detail. The blue line is the follower that seems be getting all the traffic. Green is master.

![screen shot 2016-02-19 at 8 38 52 am](https://cloud.githubusercontent.com/assets/17709/13179102/5fff1398-d6f0-11e5-8484-1d04dd0e2430.png)

**Comment by pauldowman** [comment]
I have this partly figured out. Our workload involves long-running background jobs with some slow and some fast queries. It seems that the slow queries start to collect on one instance, which slows it down further. This makes sense to me with a round-robin strategy (as opposed to routing to the most available one). 

I'm confused about how `master_strategy: failover` works though, I would have expected it to solve this, if it sticks to the same slave for all requests. Can someone confirm that each consecutive request from the same worker process _should_ hit the same database? Or might it get a different connection from the pool the next time?

I solved the problem temporarily by forcing each worker to limit itself to only one of the slave dbs (I made sure the makara config had only one slave). This worked.

**Comment by bleonard** [comment]
`failover` means that it will all got to the same one. Then if that isn't working (either dead or slow enough past the connection timeouts), it would move on to the next one. So only one is in play at a time. We've seen this be better even in master-master scenarios.

**Comment by bleonard** [comment]
There isn't currently the concept of the "most available one" - in theory you could add a strategy to do that with some additional statistics gathering.

**Comment by bleonard** [comment]
It just occurred to me that maybe you want those workers to use failover, but have each config in a different order. So that means it would prefer the top one but work down the list if it was busted. This will get you back in a spot of redundancy, which is often the original goal when using this gem.
