### ISSUE TITLE
PostgresQL - Booleans cast to ints in SQL statement?

### ISSUE THREAD

**Issue by jcmcken** [instacart/makara#112]
I'm running into a strange situation that I can't seem to figure out. I have two Postgres hosts, one is a master, and one is a read replica. I also have a Rails app connecting using the `ActiveRecord` DB adapter. 

When I use the standard `postgresql` adapter, no problems. I can even configure Rails to hit the read replica, and it connects successfully and can retrieve data (although obviously the app is not usable).

However, if I substitute in the `postgresql_makara` adapter and try to hit my app, ActiveRecord throws an exception that bubbles up from Postgres that basically amounts to:

```
PGError: ERROR: COALESCE types boolean and integer cannot be matched ...
SELECT COUNT(*) from "table_name" where COALESCE("table_name"."column_name" IS NOT NULL, 0)
```

The issue is the `COALESCE` statement, which is checking a boolean condition, but defaulting to a non-boolean (`0`).

However, if I enable the `postgresql` adapter again and hit my Rails app, I can clearly see that it's running:

```
SELECT COUNT(*) from "table_name" where COALESCE("table_name"."column_name" IS NOT NULL, false)
```

...i.e., comparing a boolean to a boolean. So the standard adapter is running the right SQL statement, but `makara` is not.

Just some additional data:

I'm running using the latest `makara` gem from rubygems.org (`0.3.5`). I'm also using PostgresQL 9.2 and Rails 3. 

Any ideas?

**Comment by jcmcken** [comment]
I've made some progress understanding what's happening, more details here: https://groups.google.com/forum/#!topic/foreman-users/-7JdhZ9XT7k

Unfortunately, I don't know enough about the internals at the moment to really understand where things are breaking down.

**Comment by jcmcken** [comment]
I'm closing this issue. This seems to be a bug in the `scoped_search` gem rather than `makara`. See wvanbergen/scoped_search#139.

**Comment by bleonard** [comment]
interesting. Is scoped search doing it's own decision logic to pick the adapter?
