### ISSUE TITLE
Unusual ammount of cached sessions

### ISSUE THREAD

**Issue by tebayoso** [instacart/makara#114]
I found out that makara is storing under /tmp/cache a huge amount of files with empty information:

```
$ cat makara%3A%3A0632f61c949413464525925c9540d126-b1059f01d8c6a77fd8585eba01610ef6 
o: ActiveSupport::Cache::Entry  :@compressedF:@expires_inf5:@created_atf1457976986.7014513:
                                                                                                @value"I"1:ET
```

Is this a normal behavior? My problem is that I run out of inodes eventually.

**Comment by bleonard** [comment]
Makara uses `Rails.cache` to keep track of stuff by default.
I assume you are using the local file cache and not clearing it.

You can set that store to anything you want.
`Makara::Cache.store = MyRedisCacheStore.new` for example.

there is a no -op store (lose some stickiness features) built in
`Makara::Cache.store = :noop`

And a memory one
`Makara::Cache.store = :memory`

**Comment by tebayoso** [comment]
Thanks for the answer! Wasn't aware of that and saved my day (forgot to come back after fixing it)

**Comment by glaksmono** [comment]
@bleonard @tebayoso I'm also having this same problem, and I'm using ActiveRecord

https://github.com/taskrabbit/makara#activerecord-database-adapter

How do you make sure that the "local file cache is cleared" eventually through the database.yml?

**Comment by NobodysNightmare** [comment]
Just in case anyone is stumbling over this issue nowadays:

Since version `0.4.0` the cache is not used at all anymore, so by upgrading, your problem would also fade away...
