### ISSUE TITLE
[HELP] Need implementation guidance

### ISSUE THREAD

**Issue by kirantpatil** [instacart/makara#115]
## Our scenarios is

1) Replicate certain User tables from Master (Cloud) to Slave (Local) and User authentication is done via Master DB

2) When there is Master DB/Internet failure the User authentication is done from Slave and the modifications to User table are saved in Slave DB

3) Once Master DB/Internet comes up, we need to apply the User DB changes from Slave to Master DB

4) After certain interval again perform step 1 (ie. replicate Master to Slave)
## Setup Details

Remote server : Microsoft SQL

Local server: Postgres/Mysql on Linux

Does makara helps me to implement this scenario ?

Please recommend the solution to achieve the same.

Thanks.

**Comment by evantahler** [comment]
I think there is some confusion here about the purpose of this tool.  Makara is a "driver" for ruby to connect to more than one database, already replicated/clustered configuration.  The databases you are connecting too need to be of the same type.  Makara also can handle the failure of one or more nodes, and allows you to configure your strategy to deal with that failure at runtime. 

This tool does not help you configure replication, nor does it provide a bridge between 2 database technologies.  If you need to write a ruby application which reads from one database technology and writes to another, you can certainly do that with ruby and the various drivers that exist, but Makara is unlikely to help you with that project.

**Comment by kirantpatil** [comment]
Thanks for your valuable reply and it really will help me.
