### ISSUE TITLE
Polymorphic relations appear to make queries against slaves even while in a transaction

### ISSUE THREAD

**Issue by choubacha** [instacart/makara#119]
It looks like makara may not be respecting being inside a transaction while making queries against a polymorphic relation.

This may only affect rails 3.2 but it's creating race conditions for me while trying to make queries against a polymorphic type. For example, if you had an `Imageable` polymorphic relation, the queries against that relation don't get stuck to master. Meaning that while in a callback you end up querying the read replica instead of master. This means that you querying outside your transaction and even if replication were perfectly in-sync, it's a different connection and the contents of the transaction are isolated from view.

Does anyone know what might be causing this and if there is a way to fix it?

edit: Setting sticky to true seems to resolve it but shouldn't be required for this to work properly.

**Comment by bleonard** [comment]
That's pretty surprising.

Have some example queries that went to the slave instead of master?
Does your debugging suggest the transaction is the problem?

**Comment by choubacha** [comment]
@bleonard I don't feel comfortable sharing our queries however, I plan on adding tests in a branch that reproduce it. I wanted to get the issue up first just in case someone else also experienced the issue.

**Comment by bleonard** [comment]
fair enough. that would be great.

**Comment by choubacha** [comment]
https://github.com/taskrabbit/makara/pull/120

@bleonard I've put together a few tests and when `sticky` is false I found two failures that will leak slave reads that should be write reads. Why this is happening 😕  I'm not sure.

**Comment by bleonard** [comment]
@kbacha copied over your specs to a branch i was working on here https://github.com/taskrabbit/makara/pull/96

i was able to reproduce without being polymorphic so took out that stuff.

**Comment by bleonard** [comment]
Merged that branch.
