### ISSUE TITLE
Tag v0.3.x Not Found

### ISSUE THREAD

**Issue by simonmorley** [instacart/makara#123]
You recommend the following:

```
gem 'makara', github: 'taskrabbit/makara', tag: 'v0.3.x'
```

Which throws an error. It's necessary to use the following instead:

```
gem 'makara', github: 'taskrabbit/makara', tag: 'v0.3.6'
```

**Comment by bleonard** [comment]
yeah, that just means to put in the newest one. think we should endeavor to keep that up to date as we bump versions? I would be worried it would fall behind.

**Comment by simonmorley** [comment]
Maybe just a note below would do.

**Comment by bleonard** [comment]
it's on rubygems now! updated readme to just use that.
