### ISSUE TITLE
[HELP] Upgrading to Rails 4.2 from 4.1.7

### ISSUE THREAD

**Issue by benlights** [instacart/makara#125]
Rails 4.2 release notes state:

> The migration DSL now supports adding and removing foreign keys. They are dumped to schema.rb as well. At this time, only the mysql, mysql2 and postgresql adapters support foreign keys.

My question is does this also apply to the mysql2_makara adapter or not?

Thank you.

**Comment by bleonard** [comment]
generally, speaking makara delegates all method calls to the "real: one like mysql2.
So it should work as expected. Please reopen if you find otherwise.
