### ISSUE TITLE
Heroku Guide

### ISSUE THREAD

**Issue by jamesfzhang** [instacart/makara#127]
Would it be possible for a maintainer to create a guide on using makara on Heroku? I'm thinking something along the lines of this: https://devcenter.heroku.com/articles/distributing-reads-to-followers-with-octopus

I'm finding the setup process for this gem to be difficult to go through for a Heroku app.

Edit: How do I know I've set this up correctly? With Octopus, I can easily see which shard a query runs on, but I'm not sure how to do that in Makara. Thanks!

**Comment by bleonard** [comment]
hmmm, we don't use heroku.

if you turn on SQL logging in Rails, it shows if it is using the Master or the Slave
`[Master|Slave] User Load (1.3ms) SELECT * FROM`users`;` for example.

**Comment by bleonard** [comment]
Anyone is free to write a heroku guide. Please let me know if you are interesting in helping or how I could help.
