### ISSUE TITLE
What is the Default expires_in for the Cache?

### ISSUE THREAD

**Issue by glaksmono** [instacart/makara#140]
I have an issue that is related to this: https://github.com/taskrabbit/makara/issues/114

Since I don't define the `config.cache_store` at all (therefore there is no `expires_in` either), I believe that it is currently using `FileStore` method. (ref: http://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-filestore)

I'm wondering on when are all of the cache will be invalidated from the `tmp/cache`?

**Comment by glaksmono** [comment]
Ah, it looks like I need to delete them manually?

http://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-filestore

```
As the cache will grow until the disk is full, it is recommended to periodically clear out old entries.
```

**Comment by bleonard** [comment]
Most people seem to use something like memcache which deletes the oldest things when it is full as well as clearing it on deploy.
