### ISSUE TITLE
Question on stickiness

### ISSUE THREAD

**Issue by lloydwatkin** [instacart/makara#142]
Just confirming what I think I know, I'm running sidekiq to do some background processes. These generally will read from the replica, however in some cases I'd like them to read from master (e.g. on posting a message).

When I call `Message.connection.stick_to_master!` do this then apply to all other database requests within this request? e.g. will a later call to `Users.messages.count` use the master connection too?

Is there a method to remove the stickiness, e.g. 

``` ruby
Message.connection.stick_to_master!
message = Message.last
Message.connection.unstick!
```

**Comment by bleonard** [comment]
we stick to master in Resque. Seems helpful.

If you have specific code that shouldn't stick you can use 

``` ruby
ActiveRecord::Base.connection.without_sticking do
  # does not stick
end
```

if you really have a reason to unset it, you would mess with the instance variable

``` ruby
  ActiveRecord::Base.connection.instance_variable_set("@master_context", nill)
```

Happy to accept a PR that has an `unstick!` method too

**Comment by lloydwatkin** [comment]
Thanks for the quick response. If I get a need for `unstick!` then I'll get a PR in, but not required for now :)
