### ISSUE TITLE
LocalJumpError: no block given (yield)

### ISSUE THREAD

**Issue by dnstevenson1** [instacart/makara#145]
We've been trying Makara v0.3.6 out in our staging environment without any problems. However, soon as we deploy to our production environment, we get an exception "LocalJumpError: no block given (yield)" anytime we attempt to save a record.

Here's the full stacktrace. I have a feeling that maybe New Relic is causing the problem? That is the only difference we have between staging & production.

Has anyone see a similar issue?

`…rd/connection_adapters/abstract/database_statements.rb:  213:in `block in transaction'
…ive_record/connection_adapters/abstract/transaction.rb:  184:in `within_new_transaction'
…rd/connection_adapters/abstract/database_statements.rb:  213:in `transaction'
(eval):61:in `block in transaction'
(eval):15:in `_makara_hijack'
(eval):57:in `transaction'
…3.0/gems/makara-0.3.6/lib/makara/connection_wrapper.rb:   99:in `public_send'
…3.0/gems/makara-0.3.6/lib/makara/connection_wrapper.rb:   99:in `method_missing'
…undle/ruby/2.3.0/gems/makara-0.3.6/lib/makara/proxy.rb:   28:in `block (3 levels) in hijack_method'
…_record/connection_adapters/makara_abstract_adapter.rb:  160:in `block in appropriate_connection'
…undle/ruby/2.3.0/gems/makara-0.3.6/lib/makara/proxy.rb:  162:in `block (3 levels) in appropriate_connection'
…undle/ruby/2.3.0/gems/makara-0.3.6/lib/makara/proxy.rb:  225:in `hijacked'
…undle/ruby/2.3.0/gems/makara-0.3.6/lib/makara/proxy.rb:  161:in `block (2 levels) in appropriate_connection'
…bundle/ruby/2.3.0/gems/makara-0.3.6/lib/makara/pool.rb:  105:in `block in provide'
…_record/connection_adapters/makara_abstract_adapter.rb:   37:in `handle'
…bundle/ruby/2.3.0/gems/makara-0.3.6/lib/makara/pool.rb:  104:in `provide'
…undle/ruby/2.3.0/gems/makara-0.3.6/lib/makara/proxy.rb:  160:in `block in appropriate_connection'
…undle/ruby/2.3.0/gems/makara-0.3.6/lib/makara/proxy.rb:  175:in `appropriate_pool'
…undle/ruby/2.3.0/gems/makara-0.3.6/lib/makara/proxy.rb:  159:in `appropriate_connection'
…_record/connection_adapters/makara_abstract_adapter.rb:  159:in `appropriate_connection'
…undle/ruby/2.3.0/gems/makara-0.3.6/lib/makara/proxy.rb:   27:in `block (2 levels) in hijack_method'
(eval):59:in `block in transaction'
(eval):17:in `_makara_hijack'
(eval):57:in `transaction'
…s/activerecord-4.2.6/lib/active_record/transactions.rb:  220:in `transaction'
…s/activerecord-4.2.6/lib/active_record/transactions.rb:  348:in `with_transaction_returning_status'
…s/activerecord-4.2.6/lib/active_record/transactions.rb:  286:in `block in save'
…s/activerecord-4.2.6/lib/active_record/transactions.rb:  301:in `rollback_active_record_state!'
…s/activerecord-4.2.6/lib/active_record/transactions.rb:  285:in `save'
…ew_relic/agent/instrumentation/active_record_helper.rb:   26:in `block in save'
…elic_rpm-3.17.2.327/lib/new_relic/agent/transaction.rb:  858:in `with_database_metric_name'
….0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent.rb:  584:in `with_database_metric_name'
…ew_relic/agent/instrumentation/active_record_helper.rb:   25:in `save'
`

**Comment by bleonard** [comment]
we've definitely seen issues with the new relic integration before.
Possible to try with it turned off to isolate?

**Comment by dnstevenson1** [comment]
I turned off New Relic gem (v3.17.2.327) by removing it from my Gemfile, restarted app, and the error did not appear. I added the gem back in and the error started immediately.

I will file a support ticket at New Relic as well with a link here.

**Comment by dnstevenson1** [comment]
@bleonard have at least ruled out that the New Relic gem is causing this. I'm still trying to reproduce in our staging environment, since this only happens on in our production environment. Differences between the two are load and in production we're pointing the slave to the same master db while we test.

**Comment by todddickerson** [comment]
any luck here?  We're seeing this as well

**Comment by nateberkopec** [comment]
@dnstevenson1 What application server are you using, and are you using any of its multithreading features?

**Comment by dnstevenson1** [comment]
We're on Apache+Passenger 5.0.29 (free version)

**Comment by nateberkopec** [comment]
Adding some more details:

* This doesn't happen all the time, only some of the time.
* Letting our processes run for longer seems to increase the frequency. Restarting them often decreases it.
* Changing thread counts of the application server has no effect. 
* Happens only when updating a record
* Doesn't seem to occur on background jobs, ever.
* We also use NewRelic.

Is it me, or is it weird that the final three lines of the stacktrace are a loop?

![screen shot 2017-05-26 at 9 11 41 am](https://cloud.githubusercontent.com/assets/845662/26500519/7342e334-41f3-11e7-8f79-0d2100236636.png)

**Comment by ryangrush** [comment]
I'm getting the same error. Here is the backtrace.

```MasterSlaveTest#test_one:
LocalJumpError: no block given (yield)
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
    (eval):61:in `block in transaction'
    (eval):15:in `_makara_hijack'
    (eval):57:in `transaction'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/connection_wrapper.rb:99:in `public_send'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/connection_wrapper.rb:99:in `method_missing'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:28:in `block (3 levels) in hijack_method'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/active_record/connection_adapters/makara_abstract_adapter.rb:160:in `block in appropriate_connection'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:165:in `block (3 levels) in appropriate_connection'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:238:in `hijacked'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:164:in `block (2 levels) in appropriate_connection'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/pool.rb:105:in `block in provide'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/active_record/connection_adapters/makara_abstract_adapter.rb:37:in `handle'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/pool.rb:104:in `provide'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:163:in `block in appropriate_connection'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:178:in `appropriate_pool'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:162:in `appropriate_connection'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/active_record/connection_adapters/makara_abstract_adapter.rb:159:in `appropriate_connection'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:27:in `block (2 levels) in hijack_method'
    (eval):59:in `block in transaction'
    (eval):17:in `_makara_hijack'
    (eval):57:in `transaction'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/referential_integrity.rb:14:in `disable_referential_integrity'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/connection_wrapper.rb:99:in `public_send'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/connection_wrapper.rb:99:in `method_missing'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:98:in `public_send'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:98:in `block in method_missing'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:145:in `block in any_connection'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/pool.rb:105:in `block in provide'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/active_record/connection_adapters/makara_abstract_adapter.rb:37:in `handle'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/pool.rb:104:in `provide'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:144:in `any_connection'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/makara-0.3.7/lib/makara/proxy.rb:96:in `method_missing'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activerecord-5.0.2/lib/active_record/fixtures.rb:523:in `create_fixtures'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activerecord-5.0.2/lib/active_record/fixtures.rb:1015:in `load_fixtures'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activerecord-5.0.2/lib/active_record/fixtures.rb:977:in `setup_fixtures'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activerecord-5.0.2/lib/active_record/fixtures.rb:852:in `before_setup'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/railties-5.0.2/lib/rails/test_help.rb:33:in `before_setup'
Error:
MasterSlaveTest#test_one:
NoMethodError: undefined method `each' for nil:NilClass
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/rails-controller-testing-1.0.1/lib/rails/controller/testing/template_assertions.rb:54:in `teardown_subscriptions'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:382:in `block in make_lambda'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:242:in `block in simple'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:456:in `block in call'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:456:in `each'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:456:in `call'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_teardown_callbacks'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activesupport-5.0.2/lib/active_support/testing/setup_and_teardown.rb:45:in `after_teardown'
    /Users/ryangrush/.rvm/gems/ruby-2.3.3@myautobrain/gems/activerecord-5.0.2/lib/active_record/fixtures.rb:857:in `after_teardown'```

**Comment by annaswims** [comment]
I saw `LocalJumpError: no block given (yield)` when upgrading to rails 5.0 and upgrading to makara 0.3.10 fixed the issue for us.

**Comment by rosa** [comment]
@annaswims right! It was fixed on https://github.com/taskrabbit/makara/pull/192. AFAIK this has always been broken but this code path was never exercised when using Rails, until recently. I imagine that NewRelic integration did use that code path before.

**Comment by mlarraz** [comment]
Closing since this was already resolved
