### ISSUE TITLE
Weird behavior - random 'select' queries are being sent to Master and not Slave!

### ISSUE THREAD

**Issue by mabdelfattah** [instacart/makara#154]
Some basic random queries are being executed on master db and not slave one! as the following
`Table.where('expiry >= NOW()')`

Which results the following query on the DB:
`use DB_NAME; SET timestamp=1493891870; SELECT COUNT(*) FROM `table` WHERE (expiry >= NOW());`

`ActiveRecord::Base.connection.select_all("Select * FROM table")`

**Comment by bleonard** [comment]
Are you saying the first query went to the wrong one, or the second one, or both?
I believe there are some issues relating to going through the `connection` like that.
This one for example: https://github.com/taskrabbit/makara/issues/148

**Comment by mabdelfattah** [comment]
Actually both went randomly to Master although when I try to execute the same queries on console, they go to slave. So, something wrong is happening, but there is an important thing to mention that is both queries were taking so long time as the DB is big... I assume that makara guessed that slave is down as it took a long time, then it tried them again on master!

**Comment by bleonard** [comment]
Specifically about the timeout issue, I believe there is a way to update the regex so it does a hard fail.

**Comment by mabdelfattah** [comment]
@bleonard any idea how to do that? As it is getting serious :) and DevOPs are complaining about that read queries that are being executed on main and not RRs.

**Comment by ikataitsev** [comment]
@mabdelfattah My two cents here. I had the same issue but then I figured that `sticky` was set to `true` (by default) and it has to be set to `false` explicitly to take effect. After the change everything started to work as expected.

**Comment by mabdelfattah** [comment]
@ikataitsev will use it for now, monitor the DB slow queries and will keep you posted.

**Comment by mabdelfattah** [comment]
It seems like `sticky: false` fixed the problem.

**Comment by kapil-kumar-roostify** [comment]
Account.find_by_id(1) is reading data from slave/1 but after onwards it reads from master always till next request for same object id 1,even i don't have any update or writes in this request.Sticky is also set to false.But from next request it's taking from slave db.

I have one master and two slaves.
