### ISSUE TITLE
Test 0.3.8.rc

### ISSUE THREAD

**Issue by bleonard** [instacart/makara#161]
@jeremy @vt-gpatrick 
I've merged your PRs.
https://github.com/taskrabbit/makara/issues/157
https://github.com/taskrabbit/makara/pull/159
https://github.com/taskrabbit/makara/pull/160

Can you please test out a release candidate?

```
# Gemfile
gem 'makara', git: 'https://github.com/taskrabbit/makara.git', tag: 'v0.3.8.rc2'
```

**Comment by bleonard** [comment]
oh wait. @jeremy has a few more. I'll review those now.

**Comment by bleonard** [comment]
@jeremy @vt-gpatrick 
I've merged your PRs.
https://github.com/taskrabbit/makara/pull/150
https://github.com/taskrabbit/makara/issues/157
https://github.com/taskrabbit/makara/pull/158
https://github.com/taskrabbit/makara/pull/159
https://github.com/taskrabbit/makara/pull/160

Can you please test out a release candidate?

```
# Gemfile
gem 'makara', git: 'https://github.com/taskrabbit/makara.git', tag: 'v0.3.8.rc3'
```

**Comment by jeremy** [comment]
Tests green. Behaved well in limited rollout. Now in production on Basecamp 3. ✅

**Comment by bleonard** [comment]
Great! 🎉  
Green here too. Waiting to test in prod until I'm back from vacation (next week).

**Comment by bleonard** [comment]
Tested and worked! Pushed new gem to rubygems.
https://rubygems.org/gems/makara

@jeremy @vt-gpatrick you can use that now it you like.
