### ISSUE TITLE
CHANGELOG: v0.3.8 details missing

### ISSUE THREAD

**Issue by etagwerker** [instacart/makara#166]
Hello,

I noticed that the CHANGELOG doesn't show the details with the changes release in v0.3.8

I see that there are a few of them: https://github.com/taskrabbit/makara/compare/v0.3.7...v0.3.8

Could you please update this file with a brief summary? 

Thank you very much!

**Comment by bleonard** [comment]
Done!

**Comment by etagwerker** [comment]
@bleonard Awesome, thanks! 👍
