### ISSUE TITLE
Makara blacklists connections due to malformed queries

### ISSUE THREAD

**Issue by justincarrao** [instacart/makara#168]
If querying for a column name that doesn't exist, for example, Makara will blacklist the connection.

Shouldn't Makara only blacklist due to connection issues?

**Comment by bleonard** [comment]
That's the intention.
this spot here says to only handle connection-related ones: https://github.com/taskrabbit/makara/blob/master/lib/active_record/connection_adapters/makara_abstract_adapter.rb#L18

What error message are you seeing?

**Comment by justincarrao** [comment]
@bleonard I believe I was mistaken, my apologies.
