### ISSUE TITLE
Travis: Trusty support

### ISSUE THREAD

**Issue by bleonard** [instacart/makara#172]
I added `precise` back to the old one, but it looks like Travis is changing their defaults.
https://travis-ci.org/taskrabbit/makara/jobs/270230777

" This job ran on our Trusty environment, which is gradually becoming our default Linux environment. Read all about this in our blog: Trusty as a default Linux is coming and take note that you can add dist: precise in your .travis.yml file to continue using Precise."

https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default

**Comment by bleonard** [comment]
issue installing `postgis` when switching to trusty.

**Comment by mlarraz** [comment]
Closing for staleness
