### ISSUE TITLE
Can Makara maintain master stickiness across cookie-less API requests?

### ISSUE THREAD

**Issue by johnwu96822** [instacart/makara#175]
Since Makara keeps track of the previous context using cookie, how can it maintain the read-after-write master stickiness across API requests, which have no cookie or session?

**Comment by bleonard** [comment]
Same note from here: https://github.com/taskrabbit/makara/issues/162

You'll have to store the "session context" guid somewhere. One way or another, that context has to be saved. In our iOS app (using AFNetworking), for example, there is a way to actually send the right cookies headers back and forth.

**Comment by johnwu96822** [comment]
@bleonard Btw I am using the AR database adapter. So I am asking in the context of Rails. The current version of Makara middleware for Rails doesn't seem to support storing the context elsewhere other than the cookie. Is there a way to accomplish that, or do I have to build my own middleware??

I don't think asking the clients to always submit and maintain cookies is the right solution. Plain RESTful APIs should not be required to maintain cookies.

**Comment by bleonard** [comment]
I'm open to solutions. The client has to maintain something. The best idea i have is to return something in the headers. Then next time, the client would have to set something on a header. That happens to be exactly how cookies works, though. So do you have another suggestion?
