### ISSUE TITLE
Empty transaction switches the next read to master

### ISSUE THREAD

**Issue by mariokostelac** [instacart/makara#177]
Rails version: 4.2.10

I have noticed that calling record.save on a model that has not changed (mysql2_makara adapter) triggers an empty transaction, which makes the context stuck on the master, causing unnecessary reads.

Repro:
```
[4] app(DEV)> identity = Model.first
  [slave/1] Model Load (0.7ms)  SELECT  `models`.*...
=> #<Model:0x007fe34c7af918 id: 1,...
[5] app(DEV)> identity.save
  [master/1] (0.6ms)  BEGIN /*app,rake_task:mario@console,line:(pry):5:in `__pry__'*/
  [master/1] (0.6ms)  COMMIT /*app,rake_task:mario@console,line:(pry):5:in `__pry__'*/
=> true
[6] app(DEV)> identity = Model.first
  [master/1] Model Load (0.8ms)  SELECT  `models`.*...
=> #<Model:0x007fe35144b588 id: 1, 
```

**Comment by mariokostelac** [comment]
Related rails issue: https://github.com/rails/rails/issues/17937

**Comment by bleonard** [comment]
As is, this is expected behavior. If there's a transaction, makara should stick to master.
