### ISSUE TITLE
Question: what is the benefit of "Stickiness"?

### ISSUE THREAD

**Issue by kigster** [instacart/makara#178]
I am not sure the README fully explains the actual reasoning behind "stickiness". When used, it doubles our `memcached` latency.

Let's say I am using 1 master and 3 replicas. At most times replicas are only a few seconds behind the master, and we generally want the traffic to round robin as much as possible to the replicas. Why would I want to stick multiple requests to the same replica, particularly across multiple Rack requests? Why is that useful? Most likely I would want to spread the traffic as evenly as possible, and have Makara automatically black list any bad replica.

Of course if one replica is simply lagging, we would ideally want to detect that and also black list this replica until it catches up.

Thanks in advance for any explanation or pointers :)

**Comment by bleonard** [comment]
I'm sure there are many possible strategies, but the use case is the following stereotypical use case on the stereotypical Rails app.

I go to a blog article and make a comment. That does a a `POST` to the server, which writes a row to the `comments` table. It then does a redirect (and a `flash` :boom:) to the blog article.

Where's my comment?! The writing and the next rendering are less than a second apart so it doesn't show up because of replica delay. Stickiness makes sure the next read is from master so that doesn't happen.

**Comment by bleonard** [comment]
Oh yeah. Hey @kigster! Long time no see!

**Comment by kigster** [comment]
Yeah! And I am only a floor below you (@ Homebase)!

OK, that makes a lot more sense now, thank you! 

However, why do we need to stick something in the distributed storage? Why can't this all be `Thread.current` specific, or at least RubyVM local.  What if we implemented something like this below? It accomplishes a similar goal, but 

1. but without any additional external IO to the cache server
2. can be configured to be a lot more granular than the global stickiness. For example, you can keep less important models be able to tolerate better replica lag. While important models like the `User` you'd ensure to auto-fallback to Makara on nil.

### Proposal

Here is [the gist](https://gist.github.com/kigster/ffb9b3437890f9a3ead77a78bbb1b226). with the proposed `Makara::AutoFailover` module, as well as `ActiveRecord::TryMaster`.

Let me know what you think!

**Comment by bleonard** [comment]
Interesting case. I'd be open to `try_master_if` if you want to make a PR.

The issue we've seen in the past would be with 
* has_many relationships: might get 3 comments but should be 4.
* the user changed their first name but it's not reflected.

It sounds like maybe you just don't want to use memcache.
I think this is the one you want. https://github.com/taskrabbit/makara/issues/162
Now that's a PR I would love!

**Comment by kigster** [comment]
@bleonard so here are my thoughts on eventual consistency with makara.

The benefit of using makara is two-fold:
1. Stability. Automatically blacklisting a replica that went down helps with four nines. At Wanelo we had replicas go offline and come back hours later, and nobody was even paged. This was a self healing incident due to makara.
2. Performance. Spreading query load across many servers helps when one db is no longer enough.

Both of these are huge. But they are not free. They come with a paradigm shift: now my application is eventually consistent. Is that a problem? It can be. But I’d argue that in 90% of the cases where a short delay may occur the user will tolerate a second or two to wait for things to update. So in most cases I think the default behavior of “the data is not there yet” should be acceptable across many apps.

Sometimes, like creating user account, you’d want to make sure you don’t make the user wait, and that’s what the `try_master_if` approach helps with: it can be applied to just some of the methods called post accounts creation, or update. 

I’d be concerned about stickiness not only because of the added overhead, but because it might mean that a lot more traffic would have to hit master than normal.

Do you guys run master so that it’s not considered a read slave, and the only reads it gets are the ones from sticky sessions?

**Comment by bleonard** [comment]
@kigster - @rosa made https://github.com/taskrabbit/makara/pull/194 to move everything to cookies. so that's pretty exciting.

**Comment by bleonard** [comment]
@kigster - try this release candidate: gem 'makara', git: 'https://github.com/taskrabbit/makara.git', tag:'v0.4.0'
