### ISSUE TITLE
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)

### ISSUE THREAD

**Issue by KiranAdroit** [instacart/makara#185]
After adding the below configuration in database.yml file and when I try to login using devise gem, it  gives this error: ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken) 

I've debug & find out its an issue from makara not from devise appeared in SessionsController

******session_store.rb
Rails.application.config.session_store :active_record_store, key: '_testapp_session', :httponly => true, :secure => false

*****database.yml
development:
  adapter: 'mysql2_makara'
  encoding: utf8
  database: 'test_db'
  makara:
    blacklist_duration: 5
    master_ttl: 5
    master_strategy: round_robin
    sticky: true
    connection_error_matchers:
      - !ruby/regexp '/^ActiveRecord::StatementInvalid: Mysql2::Error: Unknown command:/'
      - '/Sql Server Has Gone Away/'
      - 'Mysql2::Error: Duplicate entry'    
    connections:
      - role: master
        host: 127.0.0.1
        username: root
        password: 
      - role: slave
        host: 192.168.50.61
        username: root
        password: root

I'm using Rails 5.1.1 and devise 4.3.0 

When I removed below lines then its working fine. All read queries go to master.
- role: slave
        host: 192.168.50.61
        username: root
        password: root

**Comment by bleonard** [comment]
This is usually a Rails issue related to the CSRF token.

**Comment by KiranAdroit** [comment]
Yes I also thought its a Rails CSRF token issue. But when I put the slave server configuration in database.yml file then only it gives error else its working fine. Also, when I set up the only a single m/c as a master (127.0.0.1) & slave (127.0.0.1) then also its working well. But, when I set up remote IP address such as 192.168.50.61 then only it gives error for InvalidAuthenticityToken.

How to fetch particular data from the master server if all the read queries are from slave server?

Can you please look this issue as I spent whole night towards solving the issue but didn't succeed.

**Comment by bleonard** [comment]
Some stuff in the README might be helpful.

`ActiveRecord::Base.connection.stick_to_master!(true)`

```ruby
ActiveRecord::Base.connection.without_sticking do
  # do my stuff that would normally cause the proxy to stick to master
end
```

**Comment by bleonard** [comment]
@KiranAdroit ever figure this out?

**Comment by KiranAdroit** [comment]
Yes, this issue has been resolved. There was a mistake on my side. Thanks.
