### ISSUE TITLE
 v0.4.0 on rubygems?

### ISSUE THREAD

**Issue by annaswims** [instacart/makara#204]
@bleonard, I see you tagged v0.4.0 for release, but it isn't on Rubygems. Is this intentional?

**Comment by rosa** [comment]
@annaswims yes! See this comment: https://github.com/taskrabbit/makara/pull/194#issuecomment-375195718

**Comment by annaswims** [comment]
Ah, cool. Thanks!!

**Comment by bleonard** [comment]
I'm back! Thanks for the bump.
