### ISSUE TITLE
Regexp for raising blacklist connection error

### ISSUE THREAD

**Issue by johnwu96822** [instacart/makara#207]
We have an update query which raises a Mysql2::Error due to query data string being too long, which is fine since we are running mysql in strict mode. However, the problem was that the error was wrapped by blacklist connection error. Hence the connection was blacklisted, which it shouldn't be. I traced the code and found that the original exception message from Mysql2::Error (which has a huge amount of text) was handled `gracefully` due to the regexp: `/connection[^:]+closed/`

https://github.com/taskrabbit/makara/blob/v0.3.10/lib/active_record/connection_adapters/makara_abstract_adapter.rb#L25

The exception message is so big that somewhere it has the word "connection" and elsewhere it has the word "closed". Hence `/connection[^:]+closed/` matches it.

So my question is, what does the above regexp and this one:

https://github.com/taskrabbit/makara/blob/v0.3.10/lib/active_record/connection_adapters/makara_abstract_adapter.rb#L21

attempt to match? I'd like to change them to more specific pattern matching but I need to know what the target strings they were designed for. Thanks!

**Comment by bleonard** [comment]
There are several Postgres ones like this. `PG::ConnectionBad: PQconsumeInput() SSL connection has been closed unexpectedly`

**Comment by johnwu96822** [comment]
Thanks!
