### ISSUE TITLE
QUESTION: Can i use Makara with Jruby ?

### ISSUE THREAD

**Issue by fmundaca** [instacart/makara#215]
I'm use Makara for production since 2017 and its great. Recently i'm testing to change RMI for JRuby but i'm getting some errors with makara. 
It's possible to use this great gem with Jruby ? 

Thanks !

**Comment by bleonard** [comment]
The tests worked at some point I think.
Feel free to make updates as you find them.

**Comment by fmundaca** [comment]
i'll check :D 
thanks !

**Comment by fmundaca** [comment]
Update: It seems that the connection is ok but the logger show me a lot of wanings and errors
`/Users/felipealvarado/.rvm/gems/jruby-9.1.17.0/gems/makara-0.3.7/lib/makara/logging/subscriber.rb:28: warning: ObjectSpace is disabled; _id2ref only supports immediates, pass -X+O to enable`
Any idea about this ?
