### ISSUE TITLE
App displaying rendering logs after adding makara

### ISSUE THREAD

**Issue by fmluizao** [instacart/makara#231]
Hi,

I'm experiencing a strange situation after adding makara. My app are now logging all rendered views, both in production and development. If I remove makara from Gemfile, the rendering logs disappear.

```
  Rendering customers/show.html.erb within layouts/application
  Rendered customers/_search.html.erb (31.1ms)
  Rendered customers/show.html.erb within layouts/application (110.5ms)
  Rendered common/_search.html.erb (0.5ms)
  Rendered common/_flashes.html.erb (0.1ms)
  Rendered common/_launcher.html.erb (2.5ms)
```

Has anyone experienced this? I looked at the sources, but I have no clue where it came from. Is there a way to disable this behavior?

Thanks!

**Comment by fmluizao** [comment]
I was using v0.4.0. Tested with master, and the rendering logs are gone :smile: 

Would it be possible to push a new version?

**Comment by bleonard** [comment]
@rosa are you guys using master of this? I'd be happy to make you an owner to push a new version. We are not currently using makara because of infrastructure changes.

**Comment by rosa** [comment]
@bleonard yes, we are on `master` right now. We might stop using makara in favour of Rails support for primary and replicas, but we aren't there yet.

**Comment by bleonard** [comment]
Pushed up. v0.4.1
https://github.com/taskrabbit/makara/compare/v0.4.0...v0.4.1

I assume you can thank @ankane for the fix. https://github.com/taskrabbit/makara/pull/223
