### ISSUE TITLE
Adopt new reader / writer terminology 

### ISSUE THREAD

**Issue by shellandbull** [instacart/makara#257]
Hi everyone,

In accordance to recent announced changes by [Github](https://www.bbc.co.uk/news/technology-53050955) I think `makara` should also accept terminology that doesn't have a racial overtone

I would like to propose a change where the `reader`/ `writer` terminology is accepted for database roles so we can honour modern times ❤️

**Comment by colinfkennedy** [comment]
I also support this request to change the terminology used in this project.

**Comment by bleonard** [comment]
I am very happy to accept this as well, but am no longer using makara. See https://github.com/taskrabbit/makara/issues/260
Does someone want to make a pull request and test it out?

**Comment by mlarraz** [comment]
Addressed by #286 and #290
