### ISSUE TITLE
Makara maintainer request

### ISSUE THREAD

**Issue by bleonard** [instacart/makara#260]
I inherited Makara and maintained it while TaskRabbit used it. I am no longer at TaskRabbit and they are no longer using it. It makes me sad to know that I can't give it the level of attention it deserves. There are plenty of people using it and issues and PRs looking to help it improve. Can we give it a good new home?

The most likely candidates are people with recent commits - @rosa @ankane - are you interested?
Or current pull requests - @szpasztor @Kevinrob @balvig @saghaulor @sherin @montanalow @pinnymz @estraph @phil-monroe @kgunbin @kigster @earlonrails @amasses @sax

**Comment by rosa** [comment]
Hey @bleonard, thank you so much for the offering! Right now we're in a similar position. We're only using Makara for one of our apps but we're moving towards Rails's built-in support for primary-replica. I'm happy to continue helping from time to time with issues but I don't think I'd have the bandwidth to do a good job as maintainer, I'm sorry 😞

**Comment by ankane** [comment]
Hey @bleonard, thanks as well! I'm no longer at Instacart, so it's probably best to give to someone who's currently using it.

**Comment by sherin** [comment]
Hey @bleonard - thank you! I am pinging some of my teammates at Instacart and we will get back if there is interest. We do use makara extensively.

**Comment by bleonard** [comment]
Thanks @sherin -- there's a good meta story here somewhere.
I feel like this library itself needs failover to a new leader.
I suppose, because I have been unresponsive.
Hmmmm.... probably best to stop the metaphor at two levels deep. Carry on.

**Comment by sax** [comment]
Thanks for reaching out. Makara was extremely solid everywhere I've used it, but I have not worked in a Ruby codebase in the past few years, and don't think I could do it justice. Hopefully it can find a home with more attention than I could provide.

**Comment by shellandbull** [comment]
I've recently used this project and could consider becoming a maintainer of some sort 😄

**Comment by overlycommonname** [comment]
Hi @bleonard.  I'm the Director of Platform for Instacart, and we are available to become the maintainers of Makara.

**Comment by bleonard** [comment]
Great, @overlycommonname. Let's talk about a transition plan then.
It sounds like @mariogintili will be willing to help out too. Email me brian at taskrabbit dot com.

**Comment by kigster** [comment]
Makara is also in use at [Homebase](https://joinhomebase.com) — @jordanfbrown — tagging you in case you want to be involved.

**Comment by bleonard** [comment]
Progress has been made as this is now on the instacart organization. Thanks @overlycommonname @prburgu - I leave it in your hands.

**Comment by overlycommonname** [comment]
Just to update the thread, though it's already closed -- Makara is fully transfered to the instacart organization, the url is now github.com/instacart/makara

**Comment by jeremy** [comment]
Seems we're in a maintenance lull. Folks interested in joining in?
