### ISSUE TITLE
Master as slave?

### ISSUE THREAD

**Issue by clucani** [instacart/makara#265]
Hi,

I can't find the answer in the documentation and I was just wondering how I would share the selects between the master and slave, instead of just the slaves? Is it as simple as adding a slave with the master db host details?

Cheers

**Comment by bleonard** [comment]
Yes, that's right.

If you add the primary (write) replica in two spots, it will acts as a read-only follower in the other one in proportion to the other followers.

**Comment by clucani** [comment]
Great, so just to be clear for anyone else, the config would be:

connections:
      - role: master
        host: master.sql.host
      - role: slave
        host: master.sql.host
      - role: slave
        host: slave1.sql.host

Correct?

**Comment by bleonard** [comment]
yep!

**Comment by clucani** [comment]
Wonderful - thanks!
