### ISSUE TITLE
Result of the first query in multi-statement query is missing

### ISSUE THREAD

**Issue by aniketdivekar** [instacart/makara#266]
I'm running a multi-statement query using ActiveRecord with Mysql(Makara adapter) and I'm trying to store results in an array. But I don't get the result of the first query. Below is the code snippet. Please let me know what am I missing here.

### Steps to reproduce
```
ActiveRecord::Base.transaction do
    client = ActiveRecord::Base.connection.raw_connection
    test_sql = "select id, email from members where id = 1; select id, pref member_prefs where member_id = 1;"
    client.query(test_sql)
    res = []
    while client.next_result
       res << client.store_result
    end

    puts "res size: #{res.size}"
    res.each do |row|
       puts "row: #{row.to_json}"
    end
end

Output:
res size: 1
row: [[1, 3]]

If I add "select 1; " before the query, it gives me two results(though the output of the 1st query is missing)
Output:
res size: 2
row: [[1, abc@def.com]]
row: [[1, 3]]
```

### Expected behavior
The result of the first query is not returned.

### Actual behavior
It should return the result of the first query

#### Stackoverflow Link:
https://stackoverflow.com/questions/63723963/activerecord-result-of-first-query-ignored-in-multi-statement-query

### System configuration
**Rails version**:
5
**Ruby version**:
2.6.5

**Comment by levkk** [comment]
Closing issue based on your [response](https://stackoverflow.com/a/63813159/3478959) on StackOverflow.
