### ISSUE TITLE
Ruby 3.0 release only

### ISSUE THREAD

**Issue by Kevinrob** [instacart/makara#308]
We would like to use Ruby 3.0 and we use makara.

The release `v0.5.0` crash with Ruby 3.0.
The release `v0.6.0.pre` crash with `ActiveRecord::StatementInvalid: PG::ReadOnlySqlTransaction: ERROR:  cannot execute UPDATE in a read-only transaction` (this is a pre-release so I understand). 

Maybe, we can release a version `v0.5.1` with only #283 ?
Like that, everyone can use Ruby 3.0 and we can stabilise `v0.6.0.pre`.

What do you think?

**Comment by Kevinrob** [comment]
ping @scashin133 @mlarraz 😊

**Comment by dvandersluis** [comment]
I'm also trying to get Ruby 3 going and only could succeed with 0.6.0.pre but it's causing an [incompatibility](https://github.com/ankane/distribute_reads/issues/45) with the `distributed_reads` gem.

**Comment by mlarraz** [comment]
Please try https://github.com/instacart/makara/releases/tag/v0.5.1 and report back if you still see the issue.

**Comment by mlarraz** [comment]
We released this to production on our apps without issue so I'm going to mark this closed.
