### ISSUE TITLE
It should be `:replica` instead of `:primary`

### ISSUE THREAD

**Issue by hitendrasingh** [instacart/makara#356]
Hi Team,

I saw that in below line, It should be ```config[:role] = "replica"``` instead of ```config[:role] = "primary"```.
https://github.com/instacart/makara/blob/30b01111fa02ee5983007236c50de864b4a5ebcd/lib/makara/config_parser.rb#L121

I can create a PR for this issue.

**Comment by metatron1973** [comment]
System still racked with fraud gonna need forensic audit of entire system 
![Uploading 204366526...]

**Comment by 17jmumford** [comment]
Just created a PR for this, surprised it's still here several months later
