### ISSUE TITLE
Deprecation warning for Ruby3

### ISSUE THREAD

**Issue by rendy-faqot** [instacart/makara#371]
Hi, Currently I'm using makara-0.6.0.pre with Ruby 2.7.3 and I enable deprecation warning before in my server. It produces deprecation warning and it leads to makara lib [here](https://github.com/instacart/makara/blob/v035/lib/makara/proxy.rb#L75)

```
# deprecation warning
(eval):38: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

```
/app/vendor/ruby/2.7.0/gems/makara-0.6.0.pre/lib/makara/proxy.rb:133:in `method_missing'
```

I think that line was not updated to comply with Ruby3 changes (https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

Is there any plan to update the methods? 
Thank you

**Comment by lloydwatkin** [comment]
@rendy-faqot I messaged one of the creators of the project at instacart. They are no longer actively working on this project, but are happy to accept pull requests.

**Comment by rendy-faqot** [comment]
No worries, I've found the answer. The makara will check ruby environment during initiate connection, so deprecation warning log will persist as long as we are still using Ruby2.7. It will fixed automatically after running ruby in v3.

Thanks
