### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by kdonovan** [instacart/makara#73]
We have some workers that do heavy DB reads and a few writes, which looks like a perfect situation for Makara.  They operate inside a transaction, though, and it appears that that forces all subsequent reads to use the master context.  Is there any way of forcing reads to slaves while wrapped within an AR transaction?

**Comment by mnelson** [comment]
The relevant logic is wrapped up in here:

``` ruby
    def _appropriate_pool(method_name, args)
      # the args provided absolutely need master
      if needs_master?(method_name, args)
        stick_to_master(method_name, args)
        @master_pool

      # in this context, we've already stuck to master
      elsif Makara::Context.get_current == @master_context
        @master_pool

      # the previous context stuck us to master
      elsif previously_stuck_to_master?

        # we're only on master because of the previous context so
        # behave like we're sticking to master but store the current context
        stick_to_master(method_name, args, false)
        @master_pool

      # all slaves are down (or empty)
      elsif @slave_pool.completely_blacklisted?
        stick_to_master(method_name, args)
        @master_pool

      # yay! use a slave
      else
        @slave_pool
      end
    end
```

Your goal is to enable the `@slave_pool` access at the end. Any `needs_master?` usage is still relevant to your needs, but `stick_to_master` is not. You can bypass stickiness by using `without_sticking` around your transactions. Assuming you have a single master instance, you should be fine.

``` ruby
ActiveRecord::Base.connection.without_sticking do
  ActiveRecord::Base.transaction do
    worker.perform
  end
end
```

Honestly, I've never attempted this before but that's where I'd start.

**Comment by mnelson** [comment]
Also, if your workers can use a separate database.yml you could just use the `sticky:false` configuration.

**Comment by kdonovan** [comment]
Awesome, thanks Mike! I'll play around with this next week...

**Comment by Yaroslav-F** [comment]
Hi @kdonovan . Has `without_sticking` fixed the transactions problem for you in the end?
Considering applying it as well just now...

**Comment by kdonovan** [comment]
@Yaroslav-F Apologies, but my relevant side project went by the wayside long ago. FWIW I do have a vague memory that `without_sticking` helped... but sadly can't remember any of the specifics. :/

**Comment by Yaroslav-F** [comment]
Thanks @kdonovan . Asking a question on almost 4yo issue was a long shot, thanks for coming back to me.
I ran a couple of tests and it seems like without_sticking does solve the issue.
All the best!
