### ISSUE TITLE
Is makara handling syncing between master and slave DB's ?

### ISSUE THREAD

**Issue by fahim-patel** [instacart/makara#74]
As per wiki, makara handle master/slave connections. 
1. Did makara manage syncing between master and slave DB's ? 
2. IF not then please advise to achieve syncing using ruby or sql commands.

NOTE - I am using mysql.

Thanks!

**Comment by mnelson** [comment]
No, it's referred to as replication. There are tons of guides on mysql replication out there. Makara simply handles directing traffic to the appropriate db at runtime,
