### ISSUE TITLE
Option to read from master by default

### ISSUE THREAD

**Issue by ankane** [instacart/makara#77]
Hey, we use a fork of Makara that reads from master by default and replicas when explicitly called.  We use [this branch](https://github.com/taskrabbit/makara/compare/master...instacart:master-default) and the `distribute_reads` method below:

``` ruby
module DistributeReads
  def distribute_reads
    Thread.current[:distribute_reads] = true
    Makara::Context.set_current(Makara::Context.generate)
    yield
  ensure
    Thread.current[:distribute_reads] = false
  end
end

Object.send :include, DistributeReads
```

which allows you to do:

``` ruby
distribute_reads { User.count }
```

What are your thoughts on supporting a similar option or pattern out of the box?

**Comment by mnelson** [comment]
I understand that in your case you may want to do this only on occasion but in general if you're ok with some reads going to your master you can list your master db as both master and slave in the makara config.

``` yml
makara:
  connections:
    - role: master
      host: 111
    - role: slave
      host: 111
```

**Comment by yahyapo** [comment]
@ankane, I also have a similar requirement. Did this work for you?

**Comment by ankane** [comment]
@yahyapo yeah, you can [read about it here](https://github.com/ankane/shorts/blob/master/Scaling-Reads.md).

**Comment by yahyapo** [comment]
Awesome!! Thanks a lot, @ankane. Works like a charm!! :-)

**Comment by callumj** [comment]
@ankane Are you still using your monkey patch and module as a way to work around this?

**Comment by ankane** [comment]
@callumj you bet
