### ISSUE TITLE
publish latest version on rubygems

### ISSUE THREAD

**Issue by hampld** [instacart/makara#86]
Hi, 

awesome gem, thanks! Would it be possible to publish the latest version on rubygems? I'm having trouble installing the gem directly from github in my production env, unfortunately... 

Thanks!

**Comment by mnelson** [comment]
I actually haven't published this gem on rubygems at all. The one that is up there is someone else who forked and pushed it up. How are you declaring it in your gemfile?

**Comment by hampld** [comment]
Pretty much like in the readme, with

gem 'makara', github: 'taskrabbit/makara', tag: 'v0.3.3'

and for some reason the gem is not installed in my bundle on deploy (aws beanstalk)

EDIT:

ok, I kind of solved it (and it seems to be working, at least my read replica is getting connections) by changing the github: 'taskrabbit/makara' statement to git: 'https://github ...'

but when I try to open rails c, I still get an error.

https://github.com/taskrabbit/makara.git (at v0.3.3) is not yet checked out. Run `bundle install` first.

This is clearly not your fault, but the easiest remedy would be to have a published gem. Is this possible or do you oppose this?

EDIT2: 

so it seems the app now opens the connections to the slave as well, but the reads still go to master.

**Comment by mnelson** [comment]
Can you paste an obfuscated version of your database.yml? Are you executing the console via `bundle exec rails c`?

**Comment by hampld** [comment]
ok, the failed reads to the slave was a problem of the worker setup with sticky connection and has been resolved. (sorry for not updating the issue)

Yes, I execute the console through RAILS_ENV=production bundle exec rails c

**Comment by ahukkanen** [comment]
Just asking, do you have some specific reason on why not push this to rubygems as well?

**Comment by thomasbiddle** [comment]
+1 Agreed - Should really publish to Rubygems; and specify it in the README. At the **very** least - make a note that the one up there isn't official!
