### ISSUE TITLE
 Mysql2::Error: This connection is in use by: #<Thread:0x007fe04163fb40 sleep>

### ISSUE THREAD

**Issue by nikhilvs** [instacart/makara#89]
This error comes from first line of our application code, stacktrace looks like this  :
…s/makara-1ac718c7650c/lib/makara/
connection_wrapper.rb:  87:in `method_missing'
…1/bundler/gems/makara-1ac718c7650c/lib/makara/
proxy.rb:  71:in`block in method_missing'
….1/bundler/gems/makara-1ac718c7650c/lib/makara/
pool.rb:  84:in `block in provide'
…_record/connection_adapters/
makara_abstract_adapter.rb:  13:in`handle'
….1/bundler/gems/makara-1ac718c7650c/lib/makara/
pool.rb:  83:in `provide'
…1/bundler/gems/makara-1ac718c7650c/lib/makara/
proxy.rb:  69:in`method_missing'
                /home/app/api-server/app/models/
user.rb: 150:in `find_for_token_authentication'

Gemfile configuration looks like this :
makara (0.2.2)
activerecord (3.2.14)
newrelic_rpm (3.5.4.34)
newrelic-grape (1.1.0)

and also we tried below configuration hoping for an fix in this error :
 makara (0.3.3)
 activerecord (= 3.2.14)
 newrelic_rpm (3.13.0.299)
 newrelic-grape (2.0.0)

**Comment by bleonard** [comment]
@nikhilvs still seeing this?

**Comment by athirn** [comment]
we're seeing the same issue. any tips on how to debug?
