### ISSUE TITLE
ActiveRecord::StatementInvalid: Errno::EBADF: Bad file descriptor:

### ISSUE THREAD

**Issue by nikhilvs** [instacart/makara#90]
We get this error quite often on our server, below is the stack trace : 

ActiveRecord::StatementInvalid: Errno::EBADF: Bad file descriptor: ....
…1/bundler/gems/makara-b9938313f1ce/lib/makara/
proxy.rb:  23:in `block (3 levels) in hijack_method'
…_record/connection_adapters/
makara_abstract_adapter.rb: 159:in`block in appropriate_connection'
…1/bundler/gems/makara-b9938313f1ce/lib/makara/
proxy.rb: 104:in `block (3 levels) in appropriate_connection'
…1/bundler/gems/makara-b9938313f1ce/lib/makara/
proxy.rb: 167:in`hijacked'
…1/bundler/gems/makara-b9938313f1ce/lib/makara/
proxy.rb: 103:in `block (2 levels) in appropriate_connection'
….1/bundler/gems/makara-b9938313f1ce/lib/makara/
pool.rb:  93:in`block in provide'
…_record/connection_adapters/
makara_abstract_adapter.rb:  31:in `handle'
….1/bundler/gems/makara-b9938313f1ce/lib/makara/
pool.rb:  92:in`provide'
…1/bundler/gems/makara-b9938313f1ce/lib/makara/
proxy.rb: 102:in `block in appropriate_connection'
…1/bundler/gems/makara-b9938313f1ce/lib/makara/
proxy.rb: 117:in`appropriate_pool'
…1/bundler/gems/makara-b9938313f1ce/lib/makara/
proxy.rb: 101:in `appropriate_connection'
…_record/connection_adapters/
makara_abstract_adapter.rb: 158:in`appropriate_connection'
…1/bundler/gems/makara-b9938313f1ce/lib/makara/
proxy.rb:  22:in `block (2 levels) in hijack_method'
                /home/app/api-server/app/models/
user.rb: 153:in`find_for_token_authentication'

Gemfile configuration looks like this :
makara (0.2.2)
activerecord (3.2.14)
newrelic_rpm (3.5.4.34)
newrelic-grape (1.1.0)

and also we tried below configuration hoping for an fix in this error :
makara (0.3.3)
activerecord (= 3.2.14)
newrelic_rpm (3.13.0.299)
newrelic-grape (2.0.0)

**Comment by bleonard** [comment]
@nikhilvs still seeing this one?
