### ISSUE TITLE
Database adapter mysql2_makara not supported

### ISSUE THREAD

**Issue by abiacco** [instacart/makara#97]
I'm trying to use makara for the first time. I'm using v0.3.3 (mysql2 0.4.2) with AR 4.2.5, ruby 2.2.3 and rake 10.4.2.
When I try to execute my rake assets precompile task I get the error (i realize it should go to my db when i do this):

```
 [exec] ** Execute environment
 [exec] "Database adapter mysql2_makara not supported. Use:\nForeigner::Adapter.register 'mysql2_makara', 'path/to/adapter'"
```

My adapter line in database.yml is:
  adapter: mysql2_makara

I also tried makara_mysql2 and received the same error.

Suggestions?

Thanks,

-Tony

**Comment by abiacco** [comment]
After more research, i believe this is be that makara is simply unsupported in the Foreigner gem.
I've created a pull request with them to merge a change that adds makara.
https://github.com/matthuhiggins/foreigner/pull/176

**Comment by bleonard** [comment]
thanks  @abiacco - Spreading the makara the love!
